//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.18408
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillsAndTasksWebPageWcfConsumer.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.Skill))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.Task))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.DatabaseData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.Skill[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.Task[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SkillsAndTasksWebPageWcfConsumer.Service.User[]))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Skill", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class Skill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssignedToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinishedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModificationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TaskNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignedTo {
            get {
                return this.AssignedToField;
            }
            set {
                if ((this.AssignedToField.Equals(value) != true)) {
                    this.AssignedToField = value;
                    this.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinished {
            get {
                return this.IsFinishedField;
            }
            set {
                if ((this.IsFinishedField.Equals(value) != true)) {
                    this.IsFinishedField = value;
                    this.RaisePropertyChanged("IsFinished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModificationDate {
            get {
                return this.ModificationDateField;
            }
            set {
                if ((this.ModificationDateField.Equals(value) != true)) {
                    this.ModificationDateField = value;
                    this.RaisePropertyChanged("ModificationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((this.ModifiedByField.Equals(value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TaskName {
            get {
                return this.TaskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TaskNameField, value) != true)) {
                    this.TaskNameField = value;
                    this.RaisePropertyChanged("TaskName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSkill", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class UserSkill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkillId {
            get {
                return this.SkillIdField;
            }
            set {
                if ((this.SkillIdField.Equals(value) != true)) {
                    this.SkillIdField = value;
                    this.RaisePropertyChanged("SkillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatabaseData", Namespace="http://schemas.datacontract.org/2004/07/SkillsAndTasks")]
    [System.SerializableAttribute()]
    public partial class DatabaseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SkillsAndTasksWebPageWcfConsumer.Service.Skill[] SkillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SkillsAndTasksWebPageWcfConsumer.Service.Task[] TasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SkillsAndTasksWebPageWcfConsumer.Service.UserSkill[] UserSkillsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SkillsAndTasksWebPageWcfConsumer.Service.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsAndTasksWebPageWcfConsumer.Service.Skill[] Skills {
            get {
                return this.SkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillsField, value) != true)) {
                    this.SkillsField = value;
                    this.RaisePropertyChanged("Skills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsAndTasksWebPageWcfConsumer.Service.Task[] Tasks {
            get {
                return this.TasksField;
            }
            set {
                if ((object.ReferenceEquals(this.TasksField, value) != true)) {
                    this.TasksField = value;
                    this.RaisePropertyChanged("Tasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsAndTasksWebPageWcfConsumer.Service.UserSkill[] UserSkills {
            get {
                return this.UserSkillsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSkillsField, value) != true)) {
                    this.UserSkillsField = value;
                    this.RaisePropertyChanged("UserSkills");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SkillsAndTasksWebPageWcfConsumer.Service.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IMBService")]
    public interface IMBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createAccount", ReplyAction="http://tempuri.org/IMBService/createAccountResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response createAccount(SkillsAndTasksWebPageWcfConsumer.Service.User user);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/createAccount", ReplyAction="http://tempuri.org/IMBService/createAccountResponse")]
        System.IAsyncResult BegincreateAccount(SkillsAndTasksWebPageWcfConsumer.Service.User user, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndcreateAccount(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createSkill", ReplyAction="http://tempuri.org/IMBService/createSkillResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response createSkill(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/createSkill", ReplyAction="http://tempuri.org/IMBService/createSkillResponse")]
        System.IAsyncResult BegincreateSkill(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndcreateSkill(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteSkill", ReplyAction="http://tempuri.org/IMBService/deleteSkillResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response deleteSkill(int id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/deleteSkill", ReplyAction="http://tempuri.org/IMBService/deleteSkillResponse")]
        System.IAsyncResult BegindeleteSkill(int id, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EnddeleteSkill(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateSkill", ReplyAction="http://tempuri.org/IMBService/updateSkillResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response updateSkill(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/updateSkill", ReplyAction="http://tempuri.org/IMBService/updateSkillResponse")]
        System.IAsyncResult BeginupdateSkill(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndupdateSkill(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createTask", ReplyAction="http://tempuri.org/IMBService/createTaskResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response createTask(SkillsAndTasksWebPageWcfConsumer.Service.Task task);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/createTask", ReplyAction="http://tempuri.org/IMBService/createTaskResponse")]
        System.IAsyncResult BegincreateTask(SkillsAndTasksWebPageWcfConsumer.Service.Task task, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndcreateTask(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteTask", ReplyAction="http://tempuri.org/IMBService/deleteTaskResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response deleteTask(int id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/deleteTask", ReplyAction="http://tempuri.org/IMBService/deleteTaskResponse")]
        System.IAsyncResult BegindeleteTask(int id, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EnddeleteTask(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateTask", ReplyAction="http://tempuri.org/IMBService/updateTaskResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response updateTask(SkillsAndTasksWebPageWcfConsumer.Service.Task task);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/updateTask", ReplyAction="http://tempuri.org/IMBService/updateTaskResponse")]
        System.IAsyncResult BeginupdateTask(SkillsAndTasksWebPageWcfConsumer.Service.Task task, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndupdateTask(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/createUserSkill", ReplyAction="http://tempuri.org/IMBService/createUserSkillResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response createUserSkill(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/createUserSkill", ReplyAction="http://tempuri.org/IMBService/createUserSkillResponse")]
        System.IAsyncResult BegincreateUserSkill(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndcreateUserSkill(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/deleteUserSkill", ReplyAction="http://tempuri.org/IMBService/deleteUserSkillResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response deleteUserSkill(int id);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/deleteUserSkill", ReplyAction="http://tempuri.org/IMBService/deleteUserSkillResponse")]
        System.IAsyncResult BegindeleteUserSkill(int id, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EnddeleteUserSkill(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/updateUserSkill", ReplyAction="http://tempuri.org/IMBService/updateUserSkillResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response updateUserSkill(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/updateUserSkill", ReplyAction="http://tempuri.org/IMBService/updateUserSkillResponse")]
        System.IAsyncResult BeginupdateUserSkill(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndupdateUserSkill(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/loginExists", ReplyAction="http://tempuri.org/IMBService/loginExistsResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response loginExists(string name);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/loginExists", ReplyAction="http://tempuri.org/IMBService/loginExistsResponse")]
        System.IAsyncResult BeginloginExists(string name, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndloginExists(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/activateByCode", ReplyAction="http://tempuri.org/IMBService/activateByCodeResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response activateByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/activateByCode", ReplyAction="http://tempuri.org/IMBService/activateByCodeResponse")]
        System.IAsyncResult BeginactivateByCode(string code, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response EndactivateByCode(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/login", ReplyAction="http://tempuri.org/IMBService/loginResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.Response login(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/login", ReplyAction="http://tempuri.org/IMBService/loginResponse")]
        System.IAsyncResult Beginlogin(string name, string password, System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.Response Endlogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMBService/getDatabase", ReplyAction="http://tempuri.org/IMBService/getDatabaseResponse")]
        SkillsAndTasksWebPageWcfConsumer.Service.DatabaseData getDatabase();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMBService/getDatabase", ReplyAction="http://tempuri.org/IMBService/getDatabaseResponse")]
        System.IAsyncResult BegingetDatabase(System.AsyncCallback callback, object asyncState);
        
        SkillsAndTasksWebPageWcfConsumer.Service.DatabaseData EndgetDatabase(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMBServiceChannel : SkillsAndTasksWebPageWcfConsumer.Service.IMBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public createAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createSkillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public createSkillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteSkillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteSkillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateSkillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateSkillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public createTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class createUserSkillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public createUserSkillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteUserSkillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public deleteUserSkillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateUserSkillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public updateUserSkillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class loginExistsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public loginExistsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class activateByCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public activateByCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.Response)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getDatabaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getDatabaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.DatabaseData Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SkillsAndTasksWebPageWcfConsumer.Service.DatabaseData)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MBServiceClient : System.ServiceModel.ClientBase<SkillsAndTasksWebPageWcfConsumer.Service.IMBService>, SkillsAndTasksWebPageWcfConsumer.Service.IMBService {
        
        private BeginOperationDelegate onBegincreateAccountDelegate;
        
        private EndOperationDelegate onEndcreateAccountDelegate;
        
        private System.Threading.SendOrPostCallback oncreateAccountCompletedDelegate;
        
        private BeginOperationDelegate onBegincreateSkillDelegate;
        
        private EndOperationDelegate onEndcreateSkillDelegate;
        
        private System.Threading.SendOrPostCallback oncreateSkillCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteSkillDelegate;
        
        private EndOperationDelegate onEnddeleteSkillDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteSkillCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateSkillDelegate;
        
        private EndOperationDelegate onEndupdateSkillDelegate;
        
        private System.Threading.SendOrPostCallback onupdateSkillCompletedDelegate;
        
        private BeginOperationDelegate onBegincreateTaskDelegate;
        
        private EndOperationDelegate onEndcreateTaskDelegate;
        
        private System.Threading.SendOrPostCallback oncreateTaskCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteTaskDelegate;
        
        private EndOperationDelegate onEnddeleteTaskDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteTaskCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateTaskDelegate;
        
        private EndOperationDelegate onEndupdateTaskDelegate;
        
        private System.Threading.SendOrPostCallback onupdateTaskCompletedDelegate;
        
        private BeginOperationDelegate onBegincreateUserSkillDelegate;
        
        private EndOperationDelegate onEndcreateUserSkillDelegate;
        
        private System.Threading.SendOrPostCallback oncreateUserSkillCompletedDelegate;
        
        private BeginOperationDelegate onBegindeleteUserSkillDelegate;
        
        private EndOperationDelegate onEnddeleteUserSkillDelegate;
        
        private System.Threading.SendOrPostCallback ondeleteUserSkillCompletedDelegate;
        
        private BeginOperationDelegate onBeginupdateUserSkillDelegate;
        
        private EndOperationDelegate onEndupdateUserSkillDelegate;
        
        private System.Threading.SendOrPostCallback onupdateUserSkillCompletedDelegate;
        
        private BeginOperationDelegate onBeginloginExistsDelegate;
        
        private EndOperationDelegate onEndloginExistsDelegate;
        
        private System.Threading.SendOrPostCallback onloginExistsCompletedDelegate;
        
        private BeginOperationDelegate onBeginactivateByCodeDelegate;
        
        private EndOperationDelegate onEndactivateByCodeDelegate;
        
        private System.Threading.SendOrPostCallback onactivateByCodeCompletedDelegate;
        
        private BeginOperationDelegate onBeginloginDelegate;
        
        private EndOperationDelegate onEndloginDelegate;
        
        private System.Threading.SendOrPostCallback onloginCompletedDelegate;
        
        private BeginOperationDelegate onBegingetDatabaseDelegate;
        
        private EndOperationDelegate onEndgetDatabaseDelegate;
        
        private System.Threading.SendOrPostCallback ongetDatabaseCompletedDelegate;
        
        public MBServiceClient() {
        }
        
        public MBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<createAccountCompletedEventArgs> createAccountCompleted;
        
        public event System.EventHandler<createSkillCompletedEventArgs> createSkillCompleted;
        
        public event System.EventHandler<deleteSkillCompletedEventArgs> deleteSkillCompleted;
        
        public event System.EventHandler<updateSkillCompletedEventArgs> updateSkillCompleted;
        
        public event System.EventHandler<createTaskCompletedEventArgs> createTaskCompleted;
        
        public event System.EventHandler<deleteTaskCompletedEventArgs> deleteTaskCompleted;
        
        public event System.EventHandler<updateTaskCompletedEventArgs> updateTaskCompleted;
        
        public event System.EventHandler<createUserSkillCompletedEventArgs> createUserSkillCompleted;
        
        public event System.EventHandler<deleteUserSkillCompletedEventArgs> deleteUserSkillCompleted;
        
        public event System.EventHandler<updateUserSkillCompletedEventArgs> updateUserSkillCompleted;
        
        public event System.EventHandler<loginExistsCompletedEventArgs> loginExistsCompleted;
        
        public event System.EventHandler<activateByCodeCompletedEventArgs> activateByCodeCompleted;
        
        public event System.EventHandler<loginCompletedEventArgs> loginCompleted;
        
        public event System.EventHandler<getDatabaseCompletedEventArgs> getDatabaseCompleted;
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response createAccount(SkillsAndTasksWebPageWcfConsumer.Service.User user) {
            return base.Channel.createAccount(user);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegincreateAccount(SkillsAndTasksWebPageWcfConsumer.Service.User user, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincreateAccount(user, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndcreateAccount(System.IAsyncResult result) {
            return base.Channel.EndcreateAccount(result);
        }
        
        private System.IAsyncResult OnBegincreateAccount(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkillsAndTasksWebPageWcfConsumer.Service.User user = ((SkillsAndTasksWebPageWcfConsumer.Service.User)(inValues[0]));
            return this.BegincreateAccount(user, callback, asyncState);
        }
        
        private object[] OnEndcreateAccount(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndcreateAccount(result);
            return new object[] {
                    retVal};
        }
        
        private void OncreateAccountCompleted(object state) {
            if ((this.createAccountCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.createAccountCompleted(this, new createAccountCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void createAccountAsync(SkillsAndTasksWebPageWcfConsumer.Service.User user) {
            this.createAccountAsync(user, null);
        }
        
        public void createAccountAsync(SkillsAndTasksWebPageWcfConsumer.Service.User user, object userState) {
            if ((this.onBegincreateAccountDelegate == null)) {
                this.onBegincreateAccountDelegate = new BeginOperationDelegate(this.OnBegincreateAccount);
            }
            if ((this.onEndcreateAccountDelegate == null)) {
                this.onEndcreateAccountDelegate = new EndOperationDelegate(this.OnEndcreateAccount);
            }
            if ((this.oncreateAccountCompletedDelegate == null)) {
                this.oncreateAccountCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncreateAccountCompleted);
            }
            base.InvokeAsync(this.onBegincreateAccountDelegate, new object[] {
                        user}, this.onEndcreateAccountDelegate, this.oncreateAccountCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response createSkill(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill) {
            return base.Channel.createSkill(skill);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegincreateSkill(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincreateSkill(skill, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndcreateSkill(System.IAsyncResult result) {
            return base.Channel.EndcreateSkill(result);
        }
        
        private System.IAsyncResult OnBegincreateSkill(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkillsAndTasksWebPageWcfConsumer.Service.Skill skill = ((SkillsAndTasksWebPageWcfConsumer.Service.Skill)(inValues[0]));
            return this.BegincreateSkill(skill, callback, asyncState);
        }
        
        private object[] OnEndcreateSkill(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndcreateSkill(result);
            return new object[] {
                    retVal};
        }
        
        private void OncreateSkillCompleted(object state) {
            if ((this.createSkillCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.createSkillCompleted(this, new createSkillCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void createSkillAsync(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill) {
            this.createSkillAsync(skill, null);
        }
        
        public void createSkillAsync(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill, object userState) {
            if ((this.onBegincreateSkillDelegate == null)) {
                this.onBegincreateSkillDelegate = new BeginOperationDelegate(this.OnBegincreateSkill);
            }
            if ((this.onEndcreateSkillDelegate == null)) {
                this.onEndcreateSkillDelegate = new EndOperationDelegate(this.OnEndcreateSkill);
            }
            if ((this.oncreateSkillCompletedDelegate == null)) {
                this.oncreateSkillCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncreateSkillCompleted);
            }
            base.InvokeAsync(this.onBegincreateSkillDelegate, new object[] {
                        skill}, this.onEndcreateSkillDelegate, this.oncreateSkillCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response deleteSkill(int id) {
            return base.Channel.deleteSkill(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindeleteSkill(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindeleteSkill(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EnddeleteSkill(System.IAsyncResult result) {
            return base.Channel.EnddeleteSkill(result);
        }
        
        private System.IAsyncResult OnBegindeleteSkill(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BegindeleteSkill(id, callback, asyncState);
        }
        
        private object[] OnEnddeleteSkill(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EnddeleteSkill(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteSkillCompleted(object state) {
            if ((this.deleteSkillCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteSkillCompleted(this, new deleteSkillCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteSkillAsync(int id) {
            this.deleteSkillAsync(id, null);
        }
        
        public void deleteSkillAsync(int id, object userState) {
            if ((this.onBegindeleteSkillDelegate == null)) {
                this.onBegindeleteSkillDelegate = new BeginOperationDelegate(this.OnBegindeleteSkill);
            }
            if ((this.onEnddeleteSkillDelegate == null)) {
                this.onEnddeleteSkillDelegate = new EndOperationDelegate(this.OnEnddeleteSkill);
            }
            if ((this.ondeleteSkillCompletedDelegate == null)) {
                this.ondeleteSkillCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteSkillCompleted);
            }
            base.InvokeAsync(this.onBegindeleteSkillDelegate, new object[] {
                        id}, this.onEnddeleteSkillDelegate, this.ondeleteSkillCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response updateSkill(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill) {
            return base.Channel.updateSkill(skill);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateSkill(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateSkill(skill, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndupdateSkill(System.IAsyncResult result) {
            return base.Channel.EndupdateSkill(result);
        }
        
        private System.IAsyncResult OnBeginupdateSkill(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkillsAndTasksWebPageWcfConsumer.Service.Skill skill = ((SkillsAndTasksWebPageWcfConsumer.Service.Skill)(inValues[0]));
            return this.BeginupdateSkill(skill, callback, asyncState);
        }
        
        private object[] OnEndupdateSkill(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndupdateSkill(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateSkillCompleted(object state) {
            if ((this.updateSkillCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateSkillCompleted(this, new updateSkillCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateSkillAsync(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill) {
            this.updateSkillAsync(skill, null);
        }
        
        public void updateSkillAsync(SkillsAndTasksWebPageWcfConsumer.Service.Skill skill, object userState) {
            if ((this.onBeginupdateSkillDelegate == null)) {
                this.onBeginupdateSkillDelegate = new BeginOperationDelegate(this.OnBeginupdateSkill);
            }
            if ((this.onEndupdateSkillDelegate == null)) {
                this.onEndupdateSkillDelegate = new EndOperationDelegate(this.OnEndupdateSkill);
            }
            if ((this.onupdateSkillCompletedDelegate == null)) {
                this.onupdateSkillCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateSkillCompleted);
            }
            base.InvokeAsync(this.onBeginupdateSkillDelegate, new object[] {
                        skill}, this.onEndupdateSkillDelegate, this.onupdateSkillCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response createTask(SkillsAndTasksWebPageWcfConsumer.Service.Task task) {
            return base.Channel.createTask(task);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegincreateTask(SkillsAndTasksWebPageWcfConsumer.Service.Task task, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincreateTask(task, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndcreateTask(System.IAsyncResult result) {
            return base.Channel.EndcreateTask(result);
        }
        
        private System.IAsyncResult OnBegincreateTask(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkillsAndTasksWebPageWcfConsumer.Service.Task task = ((SkillsAndTasksWebPageWcfConsumer.Service.Task)(inValues[0]));
            return this.BegincreateTask(task, callback, asyncState);
        }
        
        private object[] OnEndcreateTask(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndcreateTask(result);
            return new object[] {
                    retVal};
        }
        
        private void OncreateTaskCompleted(object state) {
            if ((this.createTaskCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.createTaskCompleted(this, new createTaskCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void createTaskAsync(SkillsAndTasksWebPageWcfConsumer.Service.Task task) {
            this.createTaskAsync(task, null);
        }
        
        public void createTaskAsync(SkillsAndTasksWebPageWcfConsumer.Service.Task task, object userState) {
            if ((this.onBegincreateTaskDelegate == null)) {
                this.onBegincreateTaskDelegate = new BeginOperationDelegate(this.OnBegincreateTask);
            }
            if ((this.onEndcreateTaskDelegate == null)) {
                this.onEndcreateTaskDelegate = new EndOperationDelegate(this.OnEndcreateTask);
            }
            if ((this.oncreateTaskCompletedDelegate == null)) {
                this.oncreateTaskCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncreateTaskCompleted);
            }
            base.InvokeAsync(this.onBegincreateTaskDelegate, new object[] {
                        task}, this.onEndcreateTaskDelegate, this.oncreateTaskCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response deleteTask(int id) {
            return base.Channel.deleteTask(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindeleteTask(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindeleteTask(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EnddeleteTask(System.IAsyncResult result) {
            return base.Channel.EnddeleteTask(result);
        }
        
        private System.IAsyncResult OnBegindeleteTask(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BegindeleteTask(id, callback, asyncState);
        }
        
        private object[] OnEnddeleteTask(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EnddeleteTask(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteTaskCompleted(object state) {
            if ((this.deleteTaskCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteTaskCompleted(this, new deleteTaskCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteTaskAsync(int id) {
            this.deleteTaskAsync(id, null);
        }
        
        public void deleteTaskAsync(int id, object userState) {
            if ((this.onBegindeleteTaskDelegate == null)) {
                this.onBegindeleteTaskDelegate = new BeginOperationDelegate(this.OnBegindeleteTask);
            }
            if ((this.onEnddeleteTaskDelegate == null)) {
                this.onEnddeleteTaskDelegate = new EndOperationDelegate(this.OnEnddeleteTask);
            }
            if ((this.ondeleteTaskCompletedDelegate == null)) {
                this.ondeleteTaskCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteTaskCompleted);
            }
            base.InvokeAsync(this.onBegindeleteTaskDelegate, new object[] {
                        id}, this.onEnddeleteTaskDelegate, this.ondeleteTaskCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response updateTask(SkillsAndTasksWebPageWcfConsumer.Service.Task task) {
            return base.Channel.updateTask(task);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateTask(SkillsAndTasksWebPageWcfConsumer.Service.Task task, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateTask(task, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndupdateTask(System.IAsyncResult result) {
            return base.Channel.EndupdateTask(result);
        }
        
        private System.IAsyncResult OnBeginupdateTask(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkillsAndTasksWebPageWcfConsumer.Service.Task task = ((SkillsAndTasksWebPageWcfConsumer.Service.Task)(inValues[0]));
            return this.BeginupdateTask(task, callback, asyncState);
        }
        
        private object[] OnEndupdateTask(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndupdateTask(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateTaskCompleted(object state) {
            if ((this.updateTaskCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateTaskCompleted(this, new updateTaskCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateTaskAsync(SkillsAndTasksWebPageWcfConsumer.Service.Task task) {
            this.updateTaskAsync(task, null);
        }
        
        public void updateTaskAsync(SkillsAndTasksWebPageWcfConsumer.Service.Task task, object userState) {
            if ((this.onBeginupdateTaskDelegate == null)) {
                this.onBeginupdateTaskDelegate = new BeginOperationDelegate(this.OnBeginupdateTask);
            }
            if ((this.onEndupdateTaskDelegate == null)) {
                this.onEndupdateTaskDelegate = new EndOperationDelegate(this.OnEndupdateTask);
            }
            if ((this.onupdateTaskCompletedDelegate == null)) {
                this.onupdateTaskCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateTaskCompleted);
            }
            base.InvokeAsync(this.onBeginupdateTaskDelegate, new object[] {
                        task}, this.onEndupdateTaskDelegate, this.onupdateTaskCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response createUserSkill(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us) {
            return base.Channel.createUserSkill(us);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegincreateUserSkill(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegincreateUserSkill(us, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndcreateUserSkill(System.IAsyncResult result) {
            return base.Channel.EndcreateUserSkill(result);
        }
        
        private System.IAsyncResult OnBegincreateUserSkill(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us = ((SkillsAndTasksWebPageWcfConsumer.Service.UserSkill)(inValues[0]));
            return this.BegincreateUserSkill(us, callback, asyncState);
        }
        
        private object[] OnEndcreateUserSkill(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndcreateUserSkill(result);
            return new object[] {
                    retVal};
        }
        
        private void OncreateUserSkillCompleted(object state) {
            if ((this.createUserSkillCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.createUserSkillCompleted(this, new createUserSkillCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void createUserSkillAsync(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us) {
            this.createUserSkillAsync(us, null);
        }
        
        public void createUserSkillAsync(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us, object userState) {
            if ((this.onBegincreateUserSkillDelegate == null)) {
                this.onBegincreateUserSkillDelegate = new BeginOperationDelegate(this.OnBegincreateUserSkill);
            }
            if ((this.onEndcreateUserSkillDelegate == null)) {
                this.onEndcreateUserSkillDelegate = new EndOperationDelegate(this.OnEndcreateUserSkill);
            }
            if ((this.oncreateUserSkillCompletedDelegate == null)) {
                this.oncreateUserSkillCompletedDelegate = new System.Threading.SendOrPostCallback(this.OncreateUserSkillCompleted);
            }
            base.InvokeAsync(this.onBegincreateUserSkillDelegate, new object[] {
                        us}, this.onEndcreateUserSkillDelegate, this.oncreateUserSkillCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response deleteUserSkill(int id) {
            return base.Channel.deleteUserSkill(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegindeleteUserSkill(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegindeleteUserSkill(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EnddeleteUserSkill(System.IAsyncResult result) {
            return base.Channel.EnddeleteUserSkill(result);
        }
        
        private System.IAsyncResult OnBegindeleteUserSkill(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return this.BegindeleteUserSkill(id, callback, asyncState);
        }
        
        private object[] OnEnddeleteUserSkill(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EnddeleteUserSkill(result);
            return new object[] {
                    retVal};
        }
        
        private void OndeleteUserSkillCompleted(object state) {
            if ((this.deleteUserSkillCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.deleteUserSkillCompleted(this, new deleteUserSkillCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void deleteUserSkillAsync(int id) {
            this.deleteUserSkillAsync(id, null);
        }
        
        public void deleteUserSkillAsync(int id, object userState) {
            if ((this.onBegindeleteUserSkillDelegate == null)) {
                this.onBegindeleteUserSkillDelegate = new BeginOperationDelegate(this.OnBegindeleteUserSkill);
            }
            if ((this.onEnddeleteUserSkillDelegate == null)) {
                this.onEnddeleteUserSkillDelegate = new EndOperationDelegate(this.OnEnddeleteUserSkill);
            }
            if ((this.ondeleteUserSkillCompletedDelegate == null)) {
                this.ondeleteUserSkillCompletedDelegate = new System.Threading.SendOrPostCallback(this.OndeleteUserSkillCompleted);
            }
            base.InvokeAsync(this.onBegindeleteUserSkillDelegate, new object[] {
                        id}, this.onEnddeleteUserSkillDelegate, this.ondeleteUserSkillCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response updateUserSkill(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us) {
            return base.Channel.updateUserSkill(us);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginupdateUserSkill(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginupdateUserSkill(us, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndupdateUserSkill(System.IAsyncResult result) {
            return base.Channel.EndupdateUserSkill(result);
        }
        
        private System.IAsyncResult OnBeginupdateUserSkill(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us = ((SkillsAndTasksWebPageWcfConsumer.Service.UserSkill)(inValues[0]));
            return this.BeginupdateUserSkill(us, callback, asyncState);
        }
        
        private object[] OnEndupdateUserSkill(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndupdateUserSkill(result);
            return new object[] {
                    retVal};
        }
        
        private void OnupdateUserSkillCompleted(object state) {
            if ((this.updateUserSkillCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.updateUserSkillCompleted(this, new updateUserSkillCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void updateUserSkillAsync(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us) {
            this.updateUserSkillAsync(us, null);
        }
        
        public void updateUserSkillAsync(SkillsAndTasksWebPageWcfConsumer.Service.UserSkill us, object userState) {
            if ((this.onBeginupdateUserSkillDelegate == null)) {
                this.onBeginupdateUserSkillDelegate = new BeginOperationDelegate(this.OnBeginupdateUserSkill);
            }
            if ((this.onEndupdateUserSkillDelegate == null)) {
                this.onEndupdateUserSkillDelegate = new EndOperationDelegate(this.OnEndupdateUserSkill);
            }
            if ((this.onupdateUserSkillCompletedDelegate == null)) {
                this.onupdateUserSkillCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnupdateUserSkillCompleted);
            }
            base.InvokeAsync(this.onBeginupdateUserSkillDelegate, new object[] {
                        us}, this.onEndupdateUserSkillDelegate, this.onupdateUserSkillCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response loginExists(string name) {
            return base.Channel.loginExists(name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginloginExists(string name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginloginExists(name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndloginExists(System.IAsyncResult result) {
            return base.Channel.EndloginExists(result);
        }
        
        private System.IAsyncResult OnBeginloginExists(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            return this.BeginloginExists(name, callback, asyncState);
        }
        
        private object[] OnEndloginExists(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndloginExists(result);
            return new object[] {
                    retVal};
        }
        
        private void OnloginExistsCompleted(object state) {
            if ((this.loginExistsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.loginExistsCompleted(this, new loginExistsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void loginExistsAsync(string name) {
            this.loginExistsAsync(name, null);
        }
        
        public void loginExistsAsync(string name, object userState) {
            if ((this.onBeginloginExistsDelegate == null)) {
                this.onBeginloginExistsDelegate = new BeginOperationDelegate(this.OnBeginloginExists);
            }
            if ((this.onEndloginExistsDelegate == null)) {
                this.onEndloginExistsDelegate = new EndOperationDelegate(this.OnEndloginExists);
            }
            if ((this.onloginExistsCompletedDelegate == null)) {
                this.onloginExistsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnloginExistsCompleted);
            }
            base.InvokeAsync(this.onBeginloginExistsDelegate, new object[] {
                        name}, this.onEndloginExistsDelegate, this.onloginExistsCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response activateByCode(string code) {
            return base.Channel.activateByCode(code);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginactivateByCode(string code, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginactivateByCode(code, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response EndactivateByCode(System.IAsyncResult result) {
            return base.Channel.EndactivateByCode(result);
        }
        
        private System.IAsyncResult OnBeginactivateByCode(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string code = ((string)(inValues[0]));
            return this.BeginactivateByCode(code, callback, asyncState);
        }
        
        private object[] OnEndactivateByCode(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.EndactivateByCode(result);
            return new object[] {
                    retVal};
        }
        
        private void OnactivateByCodeCompleted(object state) {
            if ((this.activateByCodeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.activateByCodeCompleted(this, new activateByCodeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void activateByCodeAsync(string code) {
            this.activateByCodeAsync(code, null);
        }
        
        public void activateByCodeAsync(string code, object userState) {
            if ((this.onBeginactivateByCodeDelegate == null)) {
                this.onBeginactivateByCodeDelegate = new BeginOperationDelegate(this.OnBeginactivateByCode);
            }
            if ((this.onEndactivateByCodeDelegate == null)) {
                this.onEndactivateByCodeDelegate = new EndOperationDelegate(this.OnEndactivateByCode);
            }
            if ((this.onactivateByCodeCompletedDelegate == null)) {
                this.onactivateByCodeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnactivateByCodeCompleted);
            }
            base.InvokeAsync(this.onBeginactivateByCodeDelegate, new object[] {
                        code}, this.onEndactivateByCodeDelegate, this.onactivateByCodeCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.Response login(string name, string password) {
            return base.Channel.login(name, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginlogin(string name, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginlogin(name, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.Response Endlogin(System.IAsyncResult result) {
            return base.Channel.Endlogin(result);
        }
        
        private System.IAsyncResult OnBeginlogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.Beginlogin(name, password, callback, asyncState);
        }
        
        private object[] OnEndlogin(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.Response retVal = this.Endlogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnloginCompleted(object state) {
            if ((this.loginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.loginCompleted(this, new loginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void loginAsync(string name, string password) {
            this.loginAsync(name, password, null);
        }
        
        public void loginAsync(string name, string password, object userState) {
            if ((this.onBeginloginDelegate == null)) {
                this.onBeginloginDelegate = new BeginOperationDelegate(this.OnBeginlogin);
            }
            if ((this.onEndloginDelegate == null)) {
                this.onEndloginDelegate = new EndOperationDelegate(this.OnEndlogin);
            }
            if ((this.onloginCompletedDelegate == null)) {
                this.onloginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnloginCompleted);
            }
            base.InvokeAsync(this.onBeginloginDelegate, new object[] {
                        name,
                        password}, this.onEndloginDelegate, this.onloginCompletedDelegate, userState);
        }
        
        public SkillsAndTasksWebPageWcfConsumer.Service.DatabaseData getDatabase() {
            return base.Channel.getDatabase();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetDatabase(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetDatabase(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SkillsAndTasksWebPageWcfConsumer.Service.DatabaseData EndgetDatabase(System.IAsyncResult result) {
            return base.Channel.EndgetDatabase(result);
        }
        
        private System.IAsyncResult OnBegingetDatabase(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BegingetDatabase(callback, asyncState);
        }
        
        private object[] OnEndgetDatabase(System.IAsyncResult result) {
            SkillsAndTasksWebPageWcfConsumer.Service.DatabaseData retVal = this.EndgetDatabase(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetDatabaseCompleted(object state) {
            if ((this.getDatabaseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getDatabaseCompleted(this, new getDatabaseCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getDatabaseAsync() {
            this.getDatabaseAsync(null);
        }
        
        public void getDatabaseAsync(object userState) {
            if ((this.onBegingetDatabaseDelegate == null)) {
                this.onBegingetDatabaseDelegate = new BeginOperationDelegate(this.OnBegingetDatabase);
            }
            if ((this.onEndgetDatabaseDelegate == null)) {
                this.onEndgetDatabaseDelegate = new EndOperationDelegate(this.OnEndgetDatabase);
            }
            if ((this.ongetDatabaseCompletedDelegate == null)) {
                this.ongetDatabaseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetDatabaseCompleted);
            }
            base.InvokeAsync(this.onBegingetDatabaseDelegate, null, this.onEndgetDatabaseDelegate, this.ongetDatabaseCompletedDelegate, userState);
        }
    }
}
